### ISSUE TITLE
Replace `request` with `axios`

### ISSUE THREAD

**Issue by tombo1818** [loopbackio/loopback-connector-rest#147]
[request](https://github.com/request/request) is deprecated and should be replaced.

https://github.com/request/request/issues/3143

**Comment by dhmlau** [comment]
@tombo1818, thanks for bringing this up. Do you have a good alternative in mind? 
We switched to [axios](https://github.com/axios/axios) for the [loopback-next](https://github.com/strongloop/loopback-next) repo. Perhaps we should be consistent with it? 

@raymondfeng @bajtos, what do you think?

**Comment by tombo1818** [comment]
@dhmlau 
If you've also switched your loopback-next repo to axios, then loopback-connector-rest repo is also I think switching to axios is a good idea :+1:

**Comment by dhmlau** [comment]
@tombo1818, are you interested to submit a PR? Thanks.

**Comment by tombo1818** [comment]
@dhmlau I'm learning about this product, but I'm interested in PR :+1:

**Comment by dhmlau** [comment]
That's great. There's a docs page that might help you for submitting a PR: https://loopback.io/doc/en/contrib/code-contrib.html.

**Comment by bajtos** [comment]
+1 to be consistent and use the same HTTP client in all LoopBack packages.

**Comment by shivam-chouhan** [comment]
Any Update ? anybody implementing axios ?

**Comment by jaishirole** [comment]
WhiteSource has reported a vulnerability in `qs` module. The rest-connector's dependency on deprecated 'request', which in turn depends on 'qs' has been flagged. Are there any active discussions on replacing 'request' with 'axios'? I don't see any update for approx last 1+ year.

Path to vulnerable library: /node_modules/request/node_modules/qs/package.json

Dependency Hierarchy:

-> loopback-connector-rest-4.0.1.tgz (Root Library)

   -> request-2.88.2.tgz

     -> ❌ qs-6.5.3.tgz (Vulnerable Library)

**Comment by fidgi** [comment]
Note that Axios is having an issue when performing HTTPS request on HTTP proxy : [Integration of axios-https-proxy-fix](https://github.com/axios/axios/issues/4766).
Change to axios should wait until it is fixed.

**Comment by krsubbar** [comment]
Any Update ? anybody implementing axios ?

**Comment by samarpanB** [comment]
Replacing request module with axios or got or any other modern modules will require some level of re-write. So for now, we need to start by replacing the request module with a better maintained forks of it. I can see https://github.com/postmanlabs/postman-request as one of the most starred one. I am going to raise a PR for this change as of now. This will allow upgrades and security patches easier.
